//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebra.DataRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeRoleMap
    {
        public System.Guid Id { get; set; }
        public System.Guid NodeId { get; set; }
        public System.Guid RoleId { get; set; }
        public bool NonReadable { get; set; }
        public bool NonWritable { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Role Role { get; set; }
    }
}
