//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebra.DataRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUserMap
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual RoleUserMap RoleUserMaps1 { get; set; }
        public virtual RoleUserMap RoleUserMap1 { get; set; }
    }
}
