//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebra.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DTOContext : DbContext
    {
        public DTOContext()
            : base("name=TemplatesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Templates> Templates { get; set; }
        public virtual DbSet<Fields> Fields { get; set; }
        public virtual DbSet<FieldTypes> FieldTypes { get; set; }
        public virtual DbSet<TemplateFieldMap> TemplateFieldMaps { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
